<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite18f4e90bdfa02866f65337c08d1ffb4
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twilio\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twilio\\' => 
        array (
            0 => __DIR__ . '/..' . '/twilio/sdk/Twilio',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite18f4e90bdfa02866f65337c08d1ffb4::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite18f4e90bdfa02866f65337c08d1ffb4::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
